server:
  port: 8093

feign:
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types:
        - text/html
        - text/html;charset=utf-8
        - text/xml
        - text/plain
        - text/css
        - application/xml
        - application/json
        - application/json;charset=UTF-8
    response:
      enabled: true

spring:
  jackson:
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    parser:
      allow_comments: true

mandrill:
  keys:
    webhook1: dQUaYBWpVGppSGVb7rPr-A
    webhook2: 0HnHUH8oBEgpMzhVNzmmSg
