server:
  port: 8090
flyway:
  enabled: true
  schemas:
    - email

spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/hm-demo
    username: pgadmin
    password: Hotmark01!
    driver-class-name: org.postgresql.Driver
    max-idle: 1
    min-idle: 1
    max-active: 15

rendering:
  url: http://52.17.118.69/preview_smarty.php
