server:
  port: 8094

logging:
  level:
    com.hotmark.email.queue: 'DEBUG'
    com.hotmark.aws: 'DEBUG'

spring:
  metrics:
    export:
      enabled: false
      delay-millis: 1000
      send-latest: true
    sensitive: false
  jackson:
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    parser:
      allow_comments: true

mandrill:
  apiKey: Z-ribMe_9KArlJbvcP9ObQ
