server:
  port: 8090

logging:
  level:
    com.hotmark.email: 'DEBUG'
    com.hotmark.aws: 'DEBUG'
    feign: 'DEBUG'

spring:
  metrics:
    export:
      enabled: false
      send-latest: true
    sensitive: false
  jackson:
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    parser:
      allow_comments: true

rendering:
  url: http://52.17.118.69/preview_smarty.php

hotmark:
  email:
    preview: http://ec2-54-229-100-249.eu-west-1.compute.amazonaws.com:8096/email/preview
  tracker:
    baseUrl: http://ec2-54-229-100-249.eu-west-1.compute.amazonaws.com:8096
    trackOpenEndpoint: /tracker/v2/open
    trackClickEndpoint: /tracker/v2/click
    unsubscribeEndpoint: /tracker/v2/unsubscribe
