server:
  port: 8097

logging:
  level:
    com.hotmark.profile: 'DEBUG'
    feign: 'DEBUG'

spring:
  metrics:
    export:
      enabled: false
      send-latest: true
    sensitive: false
  jackson:
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    parser:
      allow_comments: true

elasticsearch:
  rate-limit: 100
  hosts:
    # -
    #   host: ec2-54-171-69-204.eu-west-1.compute.amazonaws.com
    #   port: 9300
    -
      host: 54.154.161.84
      port: 9300
    # -
    #   host: elasticsearch
    #   port: 9300
