server:
  port: 8090

logging:
  level:
    com.hotmark.txbackend: 'DEBUG'
    feign: 'DEBUG'

spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/hm-demo
    username: pgadmin
    password: Hotmark01!
    driver-class-name: org.postgresql.Driver
    max-idle: 1
    min-idle: 1
    maximum-pool-size: 2
  metrics:
    export:
      enabled: false
      send-latest: true
    sensitive: false


rendering:
  url: http://52.17.118.69/preview_smarty.php

hotmark:
  tracker:
    baseUrl: http://ec2-54-229-100-249.eu-west-1.compute.amazonaws.com:8093
    previewEndpoint: /tracker/v2/preview
    trackOpenEndpoint: /tracker/v2/open
    trackClickEndpoint: /tracker/v2/click
    unsubscribeEndpoint: /tracker/v2/unsubscribe
